# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc
import warnings

import api.proto.centri_pb2 as centri__pb2

GRPC_GENERATED_VERSION = '1.75.1'
GRPC_VERSION = grpc.__version__
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower
    _version_not_supported = first_version_is_lower(GRPC_VERSION, GRPC_GENERATED_VERSION)
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    raise RuntimeError(
        f'The grpc package installed is at version {GRPC_VERSION},'
        + f' but the generated code in centri_pb2_grpc.py depends on'
        + f' grpcio>={GRPC_GENERATED_VERSION}.'
        + f' Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}'
        + f' or downgrade your generated code using grpcio-tools<={GRPC_VERSION}.'
    )


class CentrifugoApiStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.Batch = channel.unary_unary(
                '/centrifugal.centrifugo.api.CentrifugoApi/Batch',
                request_serializer=centri__pb2.BatchRequest.SerializeToString,
                response_deserializer=centri__pb2.BatchResponse.FromString,
                _registered_method=True)
        self.Publish = channel.unary_unary(
                '/centrifugal.centrifugo.api.CentrifugoApi/Publish',
                request_serializer=centri__pb2.PublishRequest.SerializeToString,
                response_deserializer=centri__pb2.PublishResponse.FromString,
                _registered_method=True)
        self.Broadcast = channel.unary_unary(
                '/centrifugal.centrifugo.api.CentrifugoApi/Broadcast',
                request_serializer=centri__pb2.BroadcastRequest.SerializeToString,
                response_deserializer=centri__pb2.BroadcastResponse.FromString,
                _registered_method=True)
        self.Subscribe = channel.unary_unary(
                '/centrifugal.centrifugo.api.CentrifugoApi/Subscribe',
                request_serializer=centri__pb2.SubscribeRequest.SerializeToString,
                response_deserializer=centri__pb2.SubscribeResponse.FromString,
                _registered_method=True)
        self.Unsubscribe = channel.unary_unary(
                '/centrifugal.centrifugo.api.CentrifugoApi/Unsubscribe',
                request_serializer=centri__pb2.UnsubscribeRequest.SerializeToString,
                response_deserializer=centri__pb2.UnsubscribeResponse.FromString,
                _registered_method=True)
        self.Disconnect = channel.unary_unary(
                '/centrifugal.centrifugo.api.CentrifugoApi/Disconnect',
                request_serializer=centri__pb2.DisconnectRequest.SerializeToString,
                response_deserializer=centri__pb2.DisconnectResponse.FromString,
                _registered_method=True)
        self.Presence = channel.unary_unary(
                '/centrifugal.centrifugo.api.CentrifugoApi/Presence',
                request_serializer=centri__pb2.PresenceRequest.SerializeToString,
                response_deserializer=centri__pb2.PresenceResponse.FromString,
                _registered_method=True)
        self.PresenceStats = channel.unary_unary(
                '/centrifugal.centrifugo.api.CentrifugoApi/PresenceStats',
                request_serializer=centri__pb2.PresenceStatsRequest.SerializeToString,
                response_deserializer=centri__pb2.PresenceStatsResponse.FromString,
                _registered_method=True)
        self.History = channel.unary_unary(
                '/centrifugal.centrifugo.api.CentrifugoApi/History',
                request_serializer=centri__pb2.HistoryRequest.SerializeToString,
                response_deserializer=centri__pb2.HistoryResponse.FromString,
                _registered_method=True)
        self.HistoryRemove = channel.unary_unary(
                '/centrifugal.centrifugo.api.CentrifugoApi/HistoryRemove',
                request_serializer=centri__pb2.HistoryRemoveRequest.SerializeToString,
                response_deserializer=centri__pb2.HistoryRemoveResponse.FromString,
                _registered_method=True)
        self.Info = channel.unary_unary(
                '/centrifugal.centrifugo.api.CentrifugoApi/Info',
                request_serializer=centri__pb2.InfoRequest.SerializeToString,
                response_deserializer=centri__pb2.InfoResponse.FromString,
                _registered_method=True)
        self.RPC = channel.unary_unary(
                '/centrifugal.centrifugo.api.CentrifugoApi/RPC',
                request_serializer=centri__pb2.RPCRequest.SerializeToString,
                response_deserializer=centri__pb2.RPCResponse.FromString,
                _registered_method=True)
        self.Refresh = channel.unary_unary(
                '/centrifugal.centrifugo.api.CentrifugoApi/Refresh',
                request_serializer=centri__pb2.RefreshRequest.SerializeToString,
                response_deserializer=centri__pb2.RefreshResponse.FromString,
                _registered_method=True)
        self.Channels = channel.unary_unary(
                '/centrifugal.centrifugo.api.CentrifugoApi/Channels',
                request_serializer=centri__pb2.ChannelsRequest.SerializeToString,
                response_deserializer=centri__pb2.ChannelsResponse.FromString,
                _registered_method=True)
        self.Connections = channel.unary_unary(
                '/centrifugal.centrifugo.api.CentrifugoApi/Connections',
                request_serializer=centri__pb2.ConnectionsRequest.SerializeToString,
                response_deserializer=centri__pb2.ConnectionsResponse.FromString,
                _registered_method=True)
        self.UpdateUserStatus = channel.unary_unary(
                '/centrifugal.centrifugo.api.CentrifugoApi/UpdateUserStatus',
                request_serializer=centri__pb2.UpdateUserStatusRequest.SerializeToString,
                response_deserializer=centri__pb2.UpdateUserStatusResponse.FromString,
                _registered_method=True)
        self.GetUserStatus = channel.unary_unary(
                '/centrifugal.centrifugo.api.CentrifugoApi/GetUserStatus',
                request_serializer=centri__pb2.GetUserStatusRequest.SerializeToString,
                response_deserializer=centri__pb2.GetUserStatusResponse.FromString,
                _registered_method=True)
        self.DeleteUserStatus = channel.unary_unary(
                '/centrifugal.centrifugo.api.CentrifugoApi/DeleteUserStatus',
                request_serializer=centri__pb2.DeleteUserStatusRequest.SerializeToString,
                response_deserializer=centri__pb2.DeleteUserStatusResponse.FromString,
                _registered_method=True)
        self.BlockUser = channel.unary_unary(
                '/centrifugal.centrifugo.api.CentrifugoApi/BlockUser',
                request_serializer=centri__pb2.BlockUserRequest.SerializeToString,
                response_deserializer=centri__pb2.BlockUserResponse.FromString,
                _registered_method=True)
        self.UnblockUser = channel.unary_unary(
                '/centrifugal.centrifugo.api.CentrifugoApi/UnblockUser',
                request_serializer=centri__pb2.UnblockUserRequest.SerializeToString,
                response_deserializer=centri__pb2.UnblockUserResponse.FromString,
                _registered_method=True)
        self.RevokeToken = channel.unary_unary(
                '/centrifugal.centrifugo.api.CentrifugoApi/RevokeToken',
                request_serializer=centri__pb2.RevokeTokenRequest.SerializeToString,
                response_deserializer=centri__pb2.RevokeTokenResponse.FromString,
                _registered_method=True)
        self.InvalidateUserTokens = channel.unary_unary(
                '/centrifugal.centrifugo.api.CentrifugoApi/InvalidateUserTokens',
                request_serializer=centri__pb2.InvalidateUserTokensRequest.SerializeToString,
                response_deserializer=centri__pb2.InvalidateUserTokensResponse.FromString,
                _registered_method=True)
        self.DeviceRegister = channel.unary_unary(
                '/centrifugal.centrifugo.api.CentrifugoApi/DeviceRegister',
                request_serializer=centri__pb2.DeviceRegisterRequest.SerializeToString,
                response_deserializer=centri__pb2.DeviceRegisterResponse.FromString,
                _registered_method=True)
        self.DeviceUpdate = channel.unary_unary(
                '/centrifugal.centrifugo.api.CentrifugoApi/DeviceUpdate',
                request_serializer=centri__pb2.DeviceUpdateRequest.SerializeToString,
                response_deserializer=centri__pb2.DeviceUpdateResponse.FromString,
                _registered_method=True)
        self.DeviceRemove = channel.unary_unary(
                '/centrifugal.centrifugo.api.CentrifugoApi/DeviceRemove',
                request_serializer=centri__pb2.DeviceRemoveRequest.SerializeToString,
                response_deserializer=centri__pb2.DeviceRemoveResponse.FromString,
                _registered_method=True)
        self.DeviceList = channel.unary_unary(
                '/centrifugal.centrifugo.api.CentrifugoApi/DeviceList',
                request_serializer=centri__pb2.DeviceListRequest.SerializeToString,
                response_deserializer=centri__pb2.DeviceListResponse.FromString,
                _registered_method=True)
        self.DeviceTopicList = channel.unary_unary(
                '/centrifugal.centrifugo.api.CentrifugoApi/DeviceTopicList',
                request_serializer=centri__pb2.DeviceTopicListRequest.SerializeToString,
                response_deserializer=centri__pb2.DeviceTopicListResponse.FromString,
                _registered_method=True)
        self.DeviceTopicUpdate = channel.unary_unary(
                '/centrifugal.centrifugo.api.CentrifugoApi/DeviceTopicUpdate',
                request_serializer=centri__pb2.DeviceTopicUpdateRequest.SerializeToString,
                response_deserializer=centri__pb2.DeviceTopicUpdateResponse.FromString,
                _registered_method=True)
        self.UserTopicList = channel.unary_unary(
                '/centrifugal.centrifugo.api.CentrifugoApi/UserTopicList',
                request_serializer=centri__pb2.UserTopicListRequest.SerializeToString,
                response_deserializer=centri__pb2.UserTopicListResponse.FromString,
                _registered_method=True)
        self.UserTopicUpdate = channel.unary_unary(
                '/centrifugal.centrifugo.api.CentrifugoApi/UserTopicUpdate',
                request_serializer=centri__pb2.UserTopicUpdateRequest.SerializeToString,
                response_deserializer=centri__pb2.UserTopicUpdateResponse.FromString,
                _registered_method=True)
        self.SendPushNotification = channel.unary_unary(
                '/centrifugal.centrifugo.api.CentrifugoApi/SendPushNotification',
                request_serializer=centri__pb2.SendPushNotificationRequest.SerializeToString,
                response_deserializer=centri__pb2.SendPushNotificationResponse.FromString,
                _registered_method=True)
        self.UpdatePushStatus = channel.unary_unary(
                '/centrifugal.centrifugo.api.CentrifugoApi/UpdatePushStatus',
                request_serializer=centri__pb2.UpdatePushStatusRequest.SerializeToString,
                response_deserializer=centri__pb2.UpdatePushStatusResponse.FromString,
                _registered_method=True)
        self.CancelPush = channel.unary_unary(
                '/centrifugal.centrifugo.api.CentrifugoApi/CancelPush',
                request_serializer=centri__pb2.CancelPushRequest.SerializeToString,
                response_deserializer=centri__pb2.CancelPushResponse.FromString,
                _registered_method=True)


class CentrifugoApiServicer(object):
    """Missing associated documentation comment in .proto file."""

    def Batch(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def Publish(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def Broadcast(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def Subscribe(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def Unsubscribe(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def Disconnect(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def Presence(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def PresenceStats(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def History(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def HistoryRemove(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def Info(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def RPC(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def Refresh(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def Channels(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def Connections(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def UpdateUserStatus(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetUserStatus(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def DeleteUserStatus(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def BlockUser(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def UnblockUser(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def RevokeToken(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def InvalidateUserTokens(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def DeviceRegister(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def DeviceUpdate(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def DeviceRemove(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def DeviceList(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def DeviceTopicList(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def DeviceTopicUpdate(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def UserTopicList(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def UserTopicUpdate(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def SendPushNotification(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def UpdatePushStatus(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def CancelPush(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_CentrifugoApiServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'Batch': grpc.unary_unary_rpc_method_handler(
                    servicer.Batch,
                    request_deserializer=centri__pb2.BatchRequest.FromString,
                    response_serializer=centri__pb2.BatchResponse.SerializeToString,
            ),
            'Publish': grpc.unary_unary_rpc_method_handler(
                    servicer.Publish,
                    request_deserializer=centri__pb2.PublishRequest.FromString,
                    response_serializer=centri__pb2.PublishResponse.SerializeToString,
            ),
            'Broadcast': grpc.unary_unary_rpc_method_handler(
                    servicer.Broadcast,
                    request_deserializer=centri__pb2.BroadcastRequest.FromString,
                    response_serializer=centri__pb2.BroadcastResponse.SerializeToString,
            ),
            'Subscribe': grpc.unary_unary_rpc_method_handler(
                    servicer.Subscribe,
                    request_deserializer=centri__pb2.SubscribeRequest.FromString,
                    response_serializer=centri__pb2.SubscribeResponse.SerializeToString,
            ),
            'Unsubscribe': grpc.unary_unary_rpc_method_handler(
                    servicer.Unsubscribe,
                    request_deserializer=centri__pb2.UnsubscribeRequest.FromString,
                    response_serializer=centri__pb2.UnsubscribeResponse.SerializeToString,
            ),
            'Disconnect': grpc.unary_unary_rpc_method_handler(
                    servicer.Disconnect,
                    request_deserializer=centri__pb2.DisconnectRequest.FromString,
                    response_serializer=centri__pb2.DisconnectResponse.SerializeToString,
            ),
            'Presence': grpc.unary_unary_rpc_method_handler(
                    servicer.Presence,
                    request_deserializer=centri__pb2.PresenceRequest.FromString,
                    response_serializer=centri__pb2.PresenceResponse.SerializeToString,
            ),
            'PresenceStats': grpc.unary_unary_rpc_method_handler(
                    servicer.PresenceStats,
                    request_deserializer=centri__pb2.PresenceStatsRequest.FromString,
                    response_serializer=centri__pb2.PresenceStatsResponse.SerializeToString,
            ),
            'History': grpc.unary_unary_rpc_method_handler(
                    servicer.History,
                    request_deserializer=centri__pb2.HistoryRequest.FromString,
                    response_serializer=centri__pb2.HistoryResponse.SerializeToString,
            ),
            'HistoryRemove': grpc.unary_unary_rpc_method_handler(
                    servicer.HistoryRemove,
                    request_deserializer=centri__pb2.HistoryRemoveRequest.FromString,
                    response_serializer=centri__pb2.HistoryRemoveResponse.SerializeToString,
            ),
            'Info': grpc.unary_unary_rpc_method_handler(
                    servicer.Info,
                    request_deserializer=centri__pb2.InfoRequest.FromString,
                    response_serializer=centri__pb2.InfoResponse.SerializeToString,
            ),
            'RPC': grpc.unary_unary_rpc_method_handler(
                    servicer.RPC,
                    request_deserializer=centri__pb2.RPCRequest.FromString,
                    response_serializer=centri__pb2.RPCResponse.SerializeToString,
            ),
            'Refresh': grpc.unary_unary_rpc_method_handler(
                    servicer.Refresh,
                    request_deserializer=centri__pb2.RefreshRequest.FromString,
                    response_serializer=centri__pb2.RefreshResponse.SerializeToString,
            ),
            'Channels': grpc.unary_unary_rpc_method_handler(
                    servicer.Channels,
                    request_deserializer=centri__pb2.ChannelsRequest.FromString,
                    response_serializer=centri__pb2.ChannelsResponse.SerializeToString,
            ),
            'Connections': grpc.unary_unary_rpc_method_handler(
                    servicer.Connections,
                    request_deserializer=centri__pb2.ConnectionsRequest.FromString,
                    response_serializer=centri__pb2.ConnectionsResponse.SerializeToString,
            ),
            'UpdateUserStatus': grpc.unary_unary_rpc_method_handler(
                    servicer.UpdateUserStatus,
                    request_deserializer=centri__pb2.UpdateUserStatusRequest.FromString,
                    response_serializer=centri__pb2.UpdateUserStatusResponse.SerializeToString,
            ),
            'GetUserStatus': grpc.unary_unary_rpc_method_handler(
                    servicer.GetUserStatus,
                    request_deserializer=centri__pb2.GetUserStatusRequest.FromString,
                    response_serializer=centri__pb2.GetUserStatusResponse.SerializeToString,
            ),
            'DeleteUserStatus': grpc.unary_unary_rpc_method_handler(
                    servicer.DeleteUserStatus,
                    request_deserializer=centri__pb2.DeleteUserStatusRequest.FromString,
                    response_serializer=centri__pb2.DeleteUserStatusResponse.SerializeToString,
            ),
            'BlockUser': grpc.unary_unary_rpc_method_handler(
                    servicer.BlockUser,
                    request_deserializer=centri__pb2.BlockUserRequest.FromString,
                    response_serializer=centri__pb2.BlockUserResponse.SerializeToString,
            ),
            'UnblockUser': grpc.unary_unary_rpc_method_handler(
                    servicer.UnblockUser,
                    request_deserializer=centri__pb2.UnblockUserRequest.FromString,
                    response_serializer=centri__pb2.UnblockUserResponse.SerializeToString,
            ),
            'RevokeToken': grpc.unary_unary_rpc_method_handler(
                    servicer.RevokeToken,
                    request_deserializer=centri__pb2.RevokeTokenRequest.FromString,
                    response_serializer=centri__pb2.RevokeTokenResponse.SerializeToString,
            ),
            'InvalidateUserTokens': grpc.unary_unary_rpc_method_handler(
                    servicer.InvalidateUserTokens,
                    request_deserializer=centri__pb2.InvalidateUserTokensRequest.FromString,
                    response_serializer=centri__pb2.InvalidateUserTokensResponse.SerializeToString,
            ),
            'DeviceRegister': grpc.unary_unary_rpc_method_handler(
                    servicer.DeviceRegister,
                    request_deserializer=centri__pb2.DeviceRegisterRequest.FromString,
                    response_serializer=centri__pb2.DeviceRegisterResponse.SerializeToString,
            ),
            'DeviceUpdate': grpc.unary_unary_rpc_method_handler(
                    servicer.DeviceUpdate,
                    request_deserializer=centri__pb2.DeviceUpdateRequest.FromString,
                    response_serializer=centri__pb2.DeviceUpdateResponse.SerializeToString,
            ),
            'DeviceRemove': grpc.unary_unary_rpc_method_handler(
                    servicer.DeviceRemove,
                    request_deserializer=centri__pb2.DeviceRemoveRequest.FromString,
                    response_serializer=centri__pb2.DeviceRemoveResponse.SerializeToString,
            ),
            'DeviceList': grpc.unary_unary_rpc_method_handler(
                    servicer.DeviceList,
                    request_deserializer=centri__pb2.DeviceListRequest.FromString,
                    response_serializer=centri__pb2.DeviceListResponse.SerializeToString,
            ),
            'DeviceTopicList': grpc.unary_unary_rpc_method_handler(
                    servicer.DeviceTopicList,
                    request_deserializer=centri__pb2.DeviceTopicListRequest.FromString,
                    response_serializer=centri__pb2.DeviceTopicListResponse.SerializeToString,
            ),
            'DeviceTopicUpdate': grpc.unary_unary_rpc_method_handler(
                    servicer.DeviceTopicUpdate,
                    request_deserializer=centri__pb2.DeviceTopicUpdateRequest.FromString,
                    response_serializer=centri__pb2.DeviceTopicUpdateResponse.SerializeToString,
            ),
            'UserTopicList': grpc.unary_unary_rpc_method_handler(
                    servicer.UserTopicList,
                    request_deserializer=centri__pb2.UserTopicListRequest.FromString,
                    response_serializer=centri__pb2.UserTopicListResponse.SerializeToString,
            ),
            'UserTopicUpdate': grpc.unary_unary_rpc_method_handler(
                    servicer.UserTopicUpdate,
                    request_deserializer=centri__pb2.UserTopicUpdateRequest.FromString,
                    response_serializer=centri__pb2.UserTopicUpdateResponse.SerializeToString,
            ),
            'SendPushNotification': grpc.unary_unary_rpc_method_handler(
                    servicer.SendPushNotification,
                    request_deserializer=centri__pb2.SendPushNotificationRequest.FromString,
                    response_serializer=centri__pb2.SendPushNotificationResponse.SerializeToString,
            ),
            'UpdatePushStatus': grpc.unary_unary_rpc_method_handler(
                    servicer.UpdatePushStatus,
                    request_deserializer=centri__pb2.UpdatePushStatusRequest.FromString,
                    response_serializer=centri__pb2.UpdatePushStatusResponse.SerializeToString,
            ),
            'CancelPush': grpc.unary_unary_rpc_method_handler(
                    servicer.CancelPush,
                    request_deserializer=centri__pb2.CancelPushRequest.FromString,
                    response_serializer=centri__pb2.CancelPushResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'centrifugal.centrifugo.api.CentrifugoApi', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('centrifugal.centrifugo.api.CentrifugoApi', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class CentrifugoApi(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def Batch(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/centrifugal.centrifugo.api.CentrifugoApi/Batch',
            centri__pb2.BatchRequest.SerializeToString,
            centri__pb2.BatchResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def Publish(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/centrifugal.centrifugo.api.CentrifugoApi/Publish',
            centri__pb2.PublishRequest.SerializeToString,
            centri__pb2.PublishResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def Broadcast(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/centrifugal.centrifugo.api.CentrifugoApi/Broadcast',
            centri__pb2.BroadcastRequest.SerializeToString,
            centri__pb2.BroadcastResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def Subscribe(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/centrifugal.centrifugo.api.CentrifugoApi/Subscribe',
            centri__pb2.SubscribeRequest.SerializeToString,
            centri__pb2.SubscribeResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def Unsubscribe(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/centrifugal.centrifugo.api.CentrifugoApi/Unsubscribe',
            centri__pb2.UnsubscribeRequest.SerializeToString,
            centri__pb2.UnsubscribeResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def Disconnect(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/centrifugal.centrifugo.api.CentrifugoApi/Disconnect',
            centri__pb2.DisconnectRequest.SerializeToString,
            centri__pb2.DisconnectResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def Presence(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/centrifugal.centrifugo.api.CentrifugoApi/Presence',
            centri__pb2.PresenceRequest.SerializeToString,
            centri__pb2.PresenceResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def PresenceStats(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/centrifugal.centrifugo.api.CentrifugoApi/PresenceStats',
            centri__pb2.PresenceStatsRequest.SerializeToString,
            centri__pb2.PresenceStatsResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def History(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/centrifugal.centrifugo.api.CentrifugoApi/History',
            centri__pb2.HistoryRequest.SerializeToString,
            centri__pb2.HistoryResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def HistoryRemove(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/centrifugal.centrifugo.api.CentrifugoApi/HistoryRemove',
            centri__pb2.HistoryRemoveRequest.SerializeToString,
            centri__pb2.HistoryRemoveResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def Info(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/centrifugal.centrifugo.api.CentrifugoApi/Info',
            centri__pb2.InfoRequest.SerializeToString,
            centri__pb2.InfoResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def RPC(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/centrifugal.centrifugo.api.CentrifugoApi/RPC',
            centri__pb2.RPCRequest.SerializeToString,
            centri__pb2.RPCResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def Refresh(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/centrifugal.centrifugo.api.CentrifugoApi/Refresh',
            centri__pb2.RefreshRequest.SerializeToString,
            centri__pb2.RefreshResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def Channels(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/centrifugal.centrifugo.api.CentrifugoApi/Channels',
            centri__pb2.ChannelsRequest.SerializeToString,
            centri__pb2.ChannelsResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def Connections(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/centrifugal.centrifugo.api.CentrifugoApi/Connections',
            centri__pb2.ConnectionsRequest.SerializeToString,
            centri__pb2.ConnectionsResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def UpdateUserStatus(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/centrifugal.centrifugo.api.CentrifugoApi/UpdateUserStatus',
            centri__pb2.UpdateUserStatusRequest.SerializeToString,
            centri__pb2.UpdateUserStatusResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def GetUserStatus(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/centrifugal.centrifugo.api.CentrifugoApi/GetUserStatus',
            centri__pb2.GetUserStatusRequest.SerializeToString,
            centri__pb2.GetUserStatusResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def DeleteUserStatus(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/centrifugal.centrifugo.api.CentrifugoApi/DeleteUserStatus',
            centri__pb2.DeleteUserStatusRequest.SerializeToString,
            centri__pb2.DeleteUserStatusResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def BlockUser(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/centrifugal.centrifugo.api.CentrifugoApi/BlockUser',
            centri__pb2.BlockUserRequest.SerializeToString,
            centri__pb2.BlockUserResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def UnblockUser(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/centrifugal.centrifugo.api.CentrifugoApi/UnblockUser',
            centri__pb2.UnblockUserRequest.SerializeToString,
            centri__pb2.UnblockUserResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def RevokeToken(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/centrifugal.centrifugo.api.CentrifugoApi/RevokeToken',
            centri__pb2.RevokeTokenRequest.SerializeToString,
            centri__pb2.RevokeTokenResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def InvalidateUserTokens(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/centrifugal.centrifugo.api.CentrifugoApi/InvalidateUserTokens',
            centri__pb2.InvalidateUserTokensRequest.SerializeToString,
            centri__pb2.InvalidateUserTokensResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def DeviceRegister(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/centrifugal.centrifugo.api.CentrifugoApi/DeviceRegister',
            centri__pb2.DeviceRegisterRequest.SerializeToString,
            centri__pb2.DeviceRegisterResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def DeviceUpdate(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/centrifugal.centrifugo.api.CentrifugoApi/DeviceUpdate',
            centri__pb2.DeviceUpdateRequest.SerializeToString,
            centri__pb2.DeviceUpdateResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def DeviceRemove(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/centrifugal.centrifugo.api.CentrifugoApi/DeviceRemove',
            centri__pb2.DeviceRemoveRequest.SerializeToString,
            centri__pb2.DeviceRemoveResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def DeviceList(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/centrifugal.centrifugo.api.CentrifugoApi/DeviceList',
            centri__pb2.DeviceListRequest.SerializeToString,
            centri__pb2.DeviceListResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def DeviceTopicList(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/centrifugal.centrifugo.api.CentrifugoApi/DeviceTopicList',
            centri__pb2.DeviceTopicListRequest.SerializeToString,
            centri__pb2.DeviceTopicListResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def DeviceTopicUpdate(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/centrifugal.centrifugo.api.CentrifugoApi/DeviceTopicUpdate',
            centri__pb2.DeviceTopicUpdateRequest.SerializeToString,
            centri__pb2.DeviceTopicUpdateResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def UserTopicList(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/centrifugal.centrifugo.api.CentrifugoApi/UserTopicList',
            centri__pb2.UserTopicListRequest.SerializeToString,
            centri__pb2.UserTopicListResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def UserTopicUpdate(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/centrifugal.centrifugo.api.CentrifugoApi/UserTopicUpdate',
            centri__pb2.UserTopicUpdateRequest.SerializeToString,
            centri__pb2.UserTopicUpdateResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def SendPushNotification(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/centrifugal.centrifugo.api.CentrifugoApi/SendPushNotification',
            centri__pb2.SendPushNotificationRequest.SerializeToString,
            centri__pb2.SendPushNotificationResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def UpdatePushStatus(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/centrifugal.centrifugo.api.CentrifugoApi/UpdatePushStatus',
            centri__pb2.UpdatePushStatusRequest.SerializeToString,
            centri__pb2.UpdatePushStatusResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def CancelPush(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/centrifugal.centrifugo.api.CentrifugoApi/CancelPush',
            centri__pb2.CancelPushRequest.SerializeToString,
            centri__pb2.CancelPushResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
