# generated by datamodel-codegen:
#   filename:  object.py
#   timestamp: 2025-10-08T07:01:26+00:00

from __future__ import annotations

from pydantic import BaseModel, Field


class Model(BaseModel):
    field__Basic_data_structure_used_for_general_trading_function_in_the_trading_platform___: (
        str
    ) = Field(
        ...,
        alias='"\nBasic data structure used for general trading function in the trading platform.\n"',
    )
